version: "3.9"

services:
  eventstore.db:
    image: eventstore/eventstore:release-v5
    build:
      context: .
      dockerfile: EventSourcing.Api/Dockerfile
volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  eventstore-volume-index: